export const REGISTRATION_START = 'REGISTRATION_START';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED'

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const SEND_MESSAGE_START = 'SEND_MESSAGE_START';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED'

export const RECIEVE_MESSAGE_START = 'RECIEVE_MESSAGE_START';
export const RECIEVE_MESSAGE_SUCCESS = 'RECIEVE_MESSAGE_SUCCESS';
export const RECIEVE_MESSAGE_FAILED = 'RECIEVE_MESSAGE_FAILED'

export const ADD_USER = 'ADD_USER';
